//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Works = new HashSet<Work>();
        }
    
        public string ProjectID { get; set; }
        public string RequiredDeptID { get; set; }
        public string RequiredDeptPMID { get; set; }
        public string ProjectName { get; set; }
        public string EstStartDate { get; set; }
        public string EstEndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string InChargeDeptID { get; set; }
        public string InChargeDeptPMID { get; set; }
        public string ProjectStatusID { get; set; }
        public string ProjectCategoryID { get; set; }
        public string ProjectSupervisorID { get; set; }
        public Nullable<bool> IsGeneralManagerConcerned { get; set; }
        public Nullable<decimal> Budget { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work> Works { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
    }
}
