//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskResource
    {
        public string TaskID { get; set; }
        public int ResourceID { get; set; }
        public string Unit { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Date { get; set; }
        public string Description { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
