//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMEntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.TaskResources = new HashSet<TaskResource>();
        }
    
        public string WorkID { get; set; }
        public string TaskID { get; set; }
        public string TaskName { get; set; }
        public string EstStartDate { get; set; }
        public string EstEndDate { get; set; }
        public string EstWorkTime { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string WorkTime { get; set; }
        public string TaskStatusID { get; set; }
        public string EmployeeID { get; set; }
        public string Tag { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Work Work { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskResource> TaskResources { get; set; }
    }
}
